# Generated by Django 6.0.1 on 2026-01-28 10:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('request_number', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('request_text', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('R', 'Requested'), ('A', 'Accepted'), ('D', 'Denied'), ('C', 'Completed')], default='R', max_length=1)),
            ],
            options={
                'ordering': ['accepted_at'],
                'indexes': [models.Index(fields=['accepted_at'], name='changelog_c_accepte_8f3f83_idx')],
            },
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250)),
                ('body', models.TextField()),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('major_version', models.IntegerField()),
                ('current_patch', models.IntegerField()),
                ('bug_fix', models.CharField(max_length=1)),
                ('automated_post', models.BooleanField(default=False)),
                ('change_type', models.CharField(choices=[('M', 'Major'), ('P', 'Patch'), ('B', 'Bug')], default='Other', max_length=7)),
                ('status', models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published'), ('RB', 'Rolled Back')], default='DF', max_length=2)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-publish'],
                'indexes': [models.Index(fields=['-publish'], name='changelog_u_publish_0aeacc_idx')],
            },
        ),
    ]
