# Generated by Django 6.0.1 on 2026-03-23 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changelog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeRequestNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(choices=[('P', 'Pending'), ('I', 'In Progress'), ('D', 'Denied'), ('C', 'Completed')], max_length=1)),
                ('new_status', models.CharField(choices=[('P', 'Pending'), ('I', 'In Progress'), ('D', 'Denied'), ('C', 'Completed')], max_length=1)),
                ('message', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ChangeRequestTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('label', models.CharField(max_length=32)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='ChangeRequestTagAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='changerequest',
            options={'ordering': ['-updated']},
        ),
        migrations.RemoveIndex(
            model_name='changerequest',
            name='changelog_c_accepte_8f3f83_idx',
        ),
        migrations.AddField(
            model_name='changerequest',
            name='requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('I', 'In Progress'), ('D', 'Denied'), ('C', 'Completed')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='changerequestnotification',
            name='change_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='changelog.changerequest'),
        ),
        migrations.AddField(
            model_name='changerequestnotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_request_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='changerequesttagassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_change_request_tags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='changerequesttagassignment',
            name='change_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='changelog.changerequest'),
        ),
        migrations.AddField(
            model_name='changerequesttagassignment',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='changelog.changerequesttag'),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='change_requests', through='changelog.ChangeRequestTagAssignment', to='changelog.changerequesttag'),
        ),
        migrations.AddIndex(
            model_name='changerequest',
            index=models.Index(fields=['-updated'], name='changelog_c_updated_998de7_idx'),
        ),
        migrations.AddIndex(
            model_name='changerequestnotification',
            index=models.Index(fields=['user', 'is_read'], name='changelog_c_user_id_f13159_idx'),
        ),
        migrations.AddIndex(
            model_name='changerequestnotification',
            index=models.Index(fields=['-created'], name='changelog_c_created_d8f0ea_idx'),
        ),
        migrations.AddIndex(
            model_name='changerequesttagassignment',
            index=models.Index(fields=['change_request', '-assigned_at'], name='changelog_c_change__75cb76_idx'),
        ),
    ]
