# Generated by Django 6.0.1 on 2026-05-11 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changelog', '0005_githubcommit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('label', models.CharField(max_length=32)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='UpdateUpdateTagAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_update_tags', to=settings.AUTH_USER_MODEL)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='changelog.updatetag')),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='changelog.update')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.AddField(
            model_name='update',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='updates', through='changelog.UpdateUpdateTagAssignment', to='changelog.updatetag'),
        ),
        migrations.AddIndex(
            model_name='updateupdatetagassignment',
            index=models.Index(fields=['update', '-assigned_at'], name='changelog_u_update__a538b0_idx'),
        ),
    ]
