# Generated by Django 6.0.1 on 2026-01-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changelog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='version',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
