# Generated by Django 6.0.1 on 2026-01-20 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changelog', '0002_post_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='automated_post',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='change_type',
            field=models.CharField(choices=[('M', 'Major'), ('F', 'Feature'), ('W', 'Weekly'), ('B', 'Bug'), ('O', 'Other')], default='Other', max_length=7),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published'), ('RB', 'Rolled Back')], default='DF', max_length=2),
        ),
    ]
