# Generated by Django 6.0.1 on 2026-01-28 06:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changelog', '0003_post_automated_post_post_change_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250)),
                ('body', models.TextField()),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('major_version', models.CharField(max_length=3)),
                ('current_patch', models.CharField(max_length=3)),
                ('bug_fix', models.CharField(max_length=1)),
                ('automated_post', models.BooleanField(default=False)),
                ('change_type', models.CharField(choices=[('M', 'Major'), ('P', 'Patch'), ('B', 'Bug')], default='Other', max_length=7)),
                ('status', models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published'), ('RB', 'Rolled Back')], default='DF', max_length=2)),
            ],
            options={
                'ordering': ['-publish'],
            },
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='changelog_p_publish_9d1405_idx',
        ),
        migrations.AddField(
            model_name='update',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AddIndex(
            model_name='update',
            index=models.Index(fields=['-publish'], name='changelog_u_publish_0aeacc_idx'),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
