# Generated by Django 6.0.1 on 2026-03-23 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changelog', '0003_normalize_legacy_change_request_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='changerequestnotification',
            name='related_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_request_notifications', to='changelog.update'),
        ),
        migrations.CreateModel(
            name='UpdateChangeRequestLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_completed', models.BooleanField(default=False)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('change_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_links', to='changelog.changerequest')),
                ('linked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_update_change_requests', to=settings.AUTH_USER_MODEL)),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_request_links', to='changelog.update')),
            ],
            options={
                'ordering': ['-linked_at'],
            },
        ),
        migrations.AddField(
            model_name='update',
            name='change_requests',
            field=models.ManyToManyField(blank=True, related_name='updates', through='changelog.UpdateChangeRequestLink', to='changelog.changerequest'),
        ),
        migrations.AddIndex(
            model_name='updatechangerequestlink',
            index=models.Index(fields=['change_request', '-linked_at'], name='changelog_u_change__66960b_idx'),
        ),
        migrations.AddConstraint(
            model_name='updatechangerequestlink',
            constraint=models.UniqueConstraint(fields=('update', 'change_request'), name='unique_update_change_request_link'),
        ),
    ]
