# Generated by Django 6.0.1 on 2026-04-30 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changelog', '0004_changerequestnotification_related_update_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubCommit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha', models.CharField(help_text='Commit SHA (unique per repo)', max_length=40, unique=True)),
                ('message', models.TextField(help_text='Commit message')),
                ('author_name', models.CharField(help_text="Author's GitHub username", max_length=100)),
                ('author_email', models.EmailField(blank=True, help_text="Author's email (if available)", max_length=254, null=True)),
                ('date', models.DateTimeField(help_text='Commit date/time (UTC)')),
                ('repo_owner', models.CharField(help_text='GitHub repository owner', max_length=100)),
                ('repo_name', models.CharField(help_text='GitHub repository name', max_length=100)),
                ('raw_data', models.JSONField(blank=True, help_text='Raw commit data from GitHub API', null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True, help_text='When this commit was fetched from GitHub')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['-date'], name='changelog_g_date_9f0d9f_idx'), models.Index(fields=['repo_owner', 'repo_name'], name='changelog_g_repo_ow_054d90_idx')],
                'unique_together': {('sha', 'repo_owner', 'repo_name')},
            },
        ),
    ]
